[package]
name = "hawk"
version = "0.0.1"
authors = ["Jonas Finnemann Jensen <jopsen@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/taskcluster/hawk-rust"
documentation = "https://github.com/taskcluster/hawk-rust"
homepage = "https://github.com/taskcluster/hawk-rust"
description = "Hawk Implementation for rust using Hyper"

[dependencies]
hyper = "^0.10.4"
rustc-serialize = "^0.3.15"
ring = "^0.6.3"
time = "^0.1.32"
