[package]
name = "hawk"
version = "0.0.1"
authors = ["Jonas Finnemann Jensen <jopsen@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/jonasfj/hawk-rust"
documentation = "https://github.com/jonasfj/hawk-rust"
homepage = "https://github.com/jonasfj/hawk-rust"
description = "Hawk Implementation for rust using Hyper"

[dependencies]
hyper = "0.3.14"
rustc-serialize = "0.3.12"
time = "0.1.24"